export const List = [
  {
    id: 1,
    title: "EXHIBITION | MAP BENGALURU",
    img: "./assets/15.jpg",
    description: "VISIBLE/INVISIBLE:Representation of...",
    Date: "Feb 18,2023 - Dec 1,2025",
    Price: 8999,
    amount: 1
  },
  {
    id: 2,
    title: "EXHIBITION | MAP BENGALURU",
    img: "./assets/16.jpg",
    description: "Book of Gold: The Kanchana Chitra...",
    Date: "Sep 16,2023 - Mar 8,2025",
    Price: 7999,
    amount: 1
  },
  {
    id: 3,
    title: "EXHIBITION | MAP BENGALURU",
    img: "./assets/17.jpg",
    description: "What The Camera Didn't see",
    Date: "Dec 1,2023 - Mar 24,2025",
    Price: 9999,
    amount: 1
  },
];

export const Paint = [
    {
      id: 4,
      img: "./assets/p1.webp",
      description: "THE HANDMADE FLAIR Off White Mountains In The Clouds Printed Framed Canvas Wall ...",
      Price: 2760,
      amount: 1,
      title: "Free Delivery",
    },
    {
      id: 5,
      img: "./assets/p2.webp",
      description: "Perpetual Paintings for Wall Decoration - Set of 5,3d Scenery Wall Painting for you ...",
      Price: 379,
      amount: 1,
      title: "Free Delivery",
    },
    {
      id: 6,
      img: "./assets/p3.webp",
      description: "The Art House Multicoloured Abstract Painting Wall Art (Onesize) by Myntra",
      Price: 1749,
      amount: 1,
      title: "Free Delivery",
    },
    {
      id: 7,
      img: "./assets/p4.webp",
      description: "Mad Masters Lovely Couple Landscape Oil Painting 1 Piece Wooden Framed Painting ...",
      Price: 399,
      amount: 1,
      title: "Free Delivery",
    },
    {
      id: 8,
      img: "./assets/p5.webp",
      description: "Beautiful Canvas Painting with Frame for Wall Decoration A Boat Back Side View ...",
      Price: 2489,
      amount: 1,
      title: "Free Delivery",
    },
    {
      id: 9,
      img: "./assets/p6.webp",
      description: "Canvas Paintings Jai Sri Ram Painting Jai Shree ram ayodhya ram mandir",
      Price: 3800,
      amount: 1,
      title: "Free Delivery",
    },
  ];
  


export const hand = [
    {
        id: 10,
        img: "./assets/h1.webp",
        description: "Wooden Hand Painted Birds Set of 6 Woodev HandCraft...",
        Price: 315,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 11,
        img: "./assets/h2.webp",
        description: "CRAFT & CREATION- Wood and Wrought Cast Iron Mini cycle...",
        Price: 455,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 12,
        img: "./assets/h3.webp",
        description: "GUNENDRA Crafts Rajasthani Home Decor Handicrafts",
        Price: 931,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 13,
        img: "./assets/h4.webp",
        description: "Rajasthan Gems Handicraft Wooden Elephant Figure Decorative Gift Item...",
        Price: 700,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 14,
        img: "./assets/h5.jpeg",
        description: "Handmakers-Natural Hand Made Bamboo (SARKANDA) Mudda Rajasthani Stool",
        Price: 699,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 15,
        img: "./assets/h6.webp",
        description: "GoBamboos Eco-Friendly Handmade Bamboo 8.12cm x 25.4cm Steel Bottle",
        Price: 500,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 16,
        img: "./assets/h7.webp",
        description: "Handicraft Wooden Brown Handicraft And Hand-Painted Elephant Showpiece",
        Price: 3199,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 17,
        img: "./assets/h8.webp",
        description: "Hand painted Pattachitra Teapot",
        Price: 2890,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 18,
        img: "./assets/h9.webp",
        description: "7.9ft Life size Height Fairy Princess Style Cinderella's Fattonny Pumpkin Carriage for Halloween",
        Price: 7999,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 19,
        img: "./assets/h10.webp",
        description: "Beautiful Crafted Reusable Hand Candle Holders Decorative Showpiece -15cm",
        Price: 1399,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 20,
        img: "./assets/h11.webp",
        description: "Handicraft Solid Wood Home Temple...",
        Price: 1263,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 21,
        img: "./assets/h12.webp",
        description: "Hand Carved Kedarnath 3D Wooden Temple",
        Price: 549,
        amount: 1,
        title: "Free Delivery",
      },
]

export const plants =[
    {
        id: 22,
        img: "./assets/pl1.webp",
        description: "Cloud Farm Peace Lily Plant",
        Price: 129,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 23,
        img: "./assets/pl2.webp",
        description: "Mphmi Nursery Plants Live Delhi NCR Venus Flytrap, Dionaea muscipula - Plant",
        Price: 299,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 24,
        img: "./assets/pl3.webp",
        description: "The Entacloo Bird of Paradise Plant (LV-397)",
        Price: 249,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 25,
        img: "./assets/pl4.webp",
        description: "Golden Cypress Sapling - Plants - Semi-shade plant",
        Price: 69,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 26,
        img: "./assets/pl5.webp",
        description: "Washingtonia - Plant",
        Price: 1063,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 27,
        img: "./assets/pl6.webp",
        description: "Buy Laxmi Kamal Online in India | Save up to 80%",
        Price: 40,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 28,
        img: "./assets/pl7.webp",
        description: "Monstera Deliciosa - Lush Indoor Hanging Plant",
        Price: 399,
        amount: 1,
        title: "Rs. 125.00 delivery ",
      },
      {
        id: 28,
        img: "./assets/pl8.webp",
        description: "Ficus Bonsai Plant Aurelius / Grey",
        Price: 1749,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 29,
        img: "./assets/pl9.webp",
        description: "Barringtonia Acutangula Indian Oak Tree (Red Flower) Plant",
        Price: 839,
        amount: 1,
        title: "Free Delivery",
      },
]

export const books = [
    {
        id: 30,
        img: "./assets/b1.webp",
        description: "Bhagavad Gita Yatharoop Hardback",
        Price: 280,
        amount: 1,
        title: "Rs. 50.00 Delivery",
      },
      {
        id: 31,
        img: "./assets/b2.webp",
        description: "SOMETHING I NEVER TOLD YOU",
        Price: 200,
        amount: 1,
        title: "Rs. 40.00 Delivery",
      },
      {
        id: 32,
        img: "./assets/b3.webp",
        description: "THE HIDDEN HINDU",
        Price: 140,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 33,
        img: "./assets/b4.webp",
        description: "THE INTELLIGENT INVESTOR",
        Price: 199,
        amount: 1,
        title: "Rs. 100.00 Delivery",
      },
      {
        id: 34,
        img: "./assets/b5.webp",
        description: "Darius The Great Is Not Okay",
        Price: 331,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 35,
        img: "./assets/b6.webp",
        description: "Trading In The Zone",
        Price: 299,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 36,
        img: "./assets/b7.webp",
        description: "It Ends With Us Colleen Hoover",
        Price: 199,
        amount: 1,
        title: "Rs. 45.00 Delivery",
      },
      {
        id: 37,
        img: "./assets/b8.webp",
        description: "Caraval Paperback Boxed Set: Caraval, Legendary, Finale",
        Price: 2776,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 38,
        img: "./assets/b9.webp",
        description: "Moral Story Books for Kids (Set of 10 Books)Books",
        Price: 315,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 39,
        img: "./assets/b10.webp",
        description: "Indian Polity For Civil Services And Other State Examinations| 6th Revised Edition",
        Price: 799,
        amount: 1,
        title: "Rs.250.00 Delivery",
      },
      {
        id: 40,
        img: "./assets/b11.webp",
        description: "India that is Bharat : Coloniality, Civilisation, Constitution",
        Price: 399,
        amount: 1,
        title: "Free Delivery",
      },
]

