export const hand = [
    {
        id: 1,
        img: "./assets/h1.webp",
        description: "Wooden Hand Painted Birds Set of 6 Woodev HandCraft...",
        Price: 315,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 2,
        img: "./assets/h2.webp",
        description: "CRAFT & CREATION- Wood and Wrought Cast Iron Mini cycle...",
        Price: 455,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 3,
        img: "./assets/h3.webp",
        description: "GUNENDRA Crafts Rajasthani Home Decor Handicrafts",
        Price: 931,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 4,
        img: "./assets/h4.webp",
        description: "Rajasthan Gems Handicraft Wooden Elephant Figure Decorative Gift Item...",
        Price: 700,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 5,
        img: "./assets/h5.webp",
        description: "Handmakers-Natural Hand Made Bamboo (SARKANDA) Mudda Rajasthani Stool",
        Price: 699,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 6,
        img: "./assets/h6.webp",
        description: "GoBamboos Eco-Friendly Handmade Bamboo 8.12cm x 25.4cm Steel Bottle",
        Price: 500,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 7,
        img: "./assets/h7.webp",
        description: "Handicraft Wooden Brown Handicraft And Hand-Painted Elephant Showpiece",
        Price: 3199,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 8,
        img: "./assets/h8.webp",
        description: "Hand painted Pattachitra Teapot",
        Price: 2890,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 9,
        img: "./assets/h9.webp",
        description: "7.9ft Life size Height Fairy Princess Style Cinderella's Fattonny Pumpkin Carriage for Halloween",
        Price: 7999,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 10,
        img: "./assets/h10.webp",
        description: "Beautiful Crafted Reusable Hand Candle Holders Decorative Showpiece -15cm",
        Price: 1399,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 11,
        img: "./assets/h11.webp",
        description: "Handicraft Solid Wood Home Temple...",
        Price: 1263,
        amount: 1,
        title: "Free Delivery",
      },
      {
        id: 12,
        img: "./assets/h12.webp",
        description: "Hand Carved Kedarnath 3D Wooden Temple",
        Price: 549,
        amount: 1,
        title: "Free Delivery",
      },
]