export const Paint = [
  {
    id: 1,
    img: "./assets/p1.webp",
    description: "THE HANDMADE FLAIR Off White Mountains In The Clouds Printed Framed Canvas Wall ...",
    Price: 2760,
    amount: 1,
    title: "Free Delivery",
  },
  {
    id: 2,
    img: "./assets/p2.webp",
    description: "Perpetual Paintings for Wall Decoration - Set of 5,3d Scenery Wall Painting for ...",
    Price: 379,
    amount: 1,
    title: "Free Delivery",
  },
  {
    id: 3,
    img: "./assets/p3.webp",
    description: "The Art House Multicoloured Abstract Painting Wall Art (Onesize) by Myntra",
    Price: 1749,
    amount: 1,
    title: "Free Delivery",
  },
  {
    id: 4,
    img: "./assets/p4.webp",
    description: "Mad Masters Lovely Couple Landscape Oil Painting 1 Piece Wooden Framed Painting ...",
    Price: 399,
    amount: 1,
    title: "Free Delivery",
  },
  {
    id: 5,
    img: "./assets/p5.webp",
    description: "Beautiful Canvas Painting with Frame for Wall Decoration A Boat Back Side View ...",
    Price: 2489,
    amount: 1,
    title: "Free Delivery",
  },
  {
    id: 6,
    img: "./assets/p6.webp",
    description: "Canvas Paintings Jai Sri Ram Painting Jai Shree ram ayodhya ram mandir",
    Price: 3800,
    amount: 1,
    title: "Free Delivery",
  },
];
